services:
  my-db:
    container_name: review_db
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    volumes:
      - ./db:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d:ro
      - ./log:/var/log/maria
    ports:
      - 3307:3306